// Regressions for import safety, complete backup/restore, offline calendar and mobile sections.
import fs from 'node:fs';
import { serve, playwright, phone, ok, failures, FEED_FIXTURE } from './helpers.mjs';
const {chromium,devices}=await playwright(),{base,close}=await serve(),browser=await chromium.launch();
const ctx=await phone(browser,devices,{acceptDownloads:true});
const page=await ctx.newPage(),errs=[];page.on('pageerror',e=>errs.push(e.message));
const click=sel=>page.evaluate(s=>document.querySelector(s).click(),sel);
const upload=(sel,value)=>page.locator(sel).setInputFiles({name:'progress.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(value))});
const seed={traps:{'audit-record':{box:3,due:Date.now()+864e5,hist:[{at:Date.now()-16*864e5,r:'right',c:'sure'}]}},walks:{M01:{found:['step']}},prefs:{prompts:'quiet',cap:12},last:'M01'};
try{
 console.log('Data and navigation regressions');
 await page.goto(base+'#hacking/review');await page.waitForFunction(()=>!document.documentElement.classList.contains('zboot'));
 await page.evaluate(v=>localStorage.setItem('zolaB.v22',JSON.stringify(v)),seed);await page.reload();
 const previous=await page.evaluate(()=>localStorage.getItem('zolaB.v22'));
 await upload('#b-import',{data:{traps:{'audit-record':{box:1,due:0}},prefs:{cap:12,prompts:'on'}}});
 await page.waitForFunction(()=>document.querySelector('#b-io').textContent.startsWith('Import failed:'));
 ok(await page.evaluate(()=>localStorage.getItem('zolaB.v22'))===previous,'malformed Hacking import preserves exact saved progress');
 await page.reload();ok((await page.locator('#b-content').innerText()).includes('mixed review'),'review survives reload after rejected import');
 await upload('#b-import',{data:{...seed,prefs:{prompts:'bad',cap:0}}});await page.waitForFunction(()=>document.querySelector('#b-io').textContent.startsWith('Import failed:'));
 ok(await page.evaluate(()=>localStorage.getItem('zolaB.v22'))===previous,'invalid preferences preserve progress');
 const exported=await Promise.all([page.waitForEvent('download'),click('#b-export')]);
 const bfile=JSON.parse(fs.readFileSync(await exported[0].path(),'utf8'));
 page.once('dialog',d=>d.dismiss());await upload('#b-import',bfile);await page.waitForTimeout(100);
 ok(await page.evaluate(()=>localStorage.getItem('zolaB.v22'))===previous,'cancelling a valid import preserves progress');
 await page.evaluate(()=>localStorage.removeItem('zolaB.v22'));await page.reload();
 page.once('dialog',d=>d.accept());await upload('#b-import',bfile);await page.waitForFunction(()=>document.querySelector('#b-io').textContent.startsWith('Imported.'));
 ok(await page.evaluate(()=>localStorage.getItem('zolaB.v22'))===previous,'valid Hacking export/import round trip preserves all records');
 // A denied storage write must not change in-memory progress either.
 await page.evaluate(()=>{window.__set=Storage.prototype.setItem;Storage.prototype.setItem=function(k,v){if(k==='zolaB.v22')throw new Error('Storage unavailable');return window.__set.call(this,k,v)}});
 page.once('dialog',d=>d.accept());await upload('#b-import',{data:{...seed,traps:{}}});await page.waitForFunction(()=>document.querySelector('#b-io').textContent.startsWith('Import failed:'));
 await page.evaluate(()=>Storage.prototype.setItem=window.__set);
 ok(await page.evaluate(()=>localStorage.getItem('zolaB.v22'))===previous,'failed import storage writes preserve existing progress');
 await click('#tab-csat');await page.waitForTimeout(500);const frame=page.frames().find(f=>f!==page.mainFrame());
 await frame.evaluate(()=>{document.querySelector('#forgeQ .opt').click();document.querySelector('#fconf [data-c="half"]').click();document.querySelector('#fInk').click();document.querySelector('[data-go="mock"]').click();document.querySelector('#mBp').value='sprint';document.querySelector('#mStart').click()});
 ok(await page.evaluate(()=>{try{const s=JSON.parse(localStorage.getItem('zolaCsatForge.v1'));ZOLA_DATA.csat(s);return s.ledger.length===1&&s.live.qs.length===20}catch(e){return false}}),'real CSAT answers and an unfinished paper pass restore validation');
 for(let i=0;i<3;i++){await click('#themeBtn');await page.waitForTimeout(100);ok(await frame.evaluate(()=>document.documentElement.dataset.theme)===await page.evaluate(()=>document.documentElement.dataset.theme),'CSAT theme follows header on toggle '+(i+1));}
 ok(await frame.evaluate(()=>getComputedStyle(document.querySelector('#themeBtn')).display==='none'),'CSAT duplicate theme button remains hidden');
 await click('#tab-forecast');await page.evaluate(()=>location.hash='#forecast/brief');await page.waitForTimeout(300);
 await page.waitForFunction(()=>document.querySelector('#zbackup-reminder'));
 ok(true,'progress older than 14 days gets a backup reminder');
 await page.reload();await page.waitForTimeout(3200);
 ok(await page.locator('#zbackup-reminder').count()===0,'backup reminder is quiet on subsequent visits');
 await page.evaluate(()=>localStorage.setItem('other-app.keep','untouched'));
 const [download]=await Promise.all([page.waitForEvent('download'),click('#zbackup-save')]);
 const backup=JSON.parse(fs.readFileSync(await download.path(),'utf8'));
 ok(backup.storage['zolaB.v22']===previous&&!!backup.storage['zolaCsatForge.v1']&&!!backup.storage['zolaV2.theme'],'full backup includes Hacking, CSAT and Forecast values');
 ok(!Object.hasOwn(backup.storage,'other-app.keep'),'backup excludes unrelated application data');
 await page.evaluate(()=>{Object.keys(localStorage).filter(ZOLA_DATA.storageKey).forEach(k=>localStorage.removeItem(k));localStorage.setItem('zola.pwa.extraAfterBackup','remove on restore')});
 await upload('#zbackup-file',backup);await page.waitForFunction(()=>document.querySelector('#zbackup').open);
 ok((await page.locator('#zbackup-summary').innerText()).includes('one unfinished paper'),'restore previews counts, date, edition and unfinished paper');
 await click('#zbackup-cancel');
 ok(await page.evaluate(()=>localStorage.getItem('zolaB.v22'))===null,'cancelling restore makes no storage changes');
 const restored=await page.evaluate(v=>{ZOLA_BACKUP.restore(v);return {storage:ZOLA_BACKUP.snapshot().storage,other:localStorage.getItem('other-app.keep')}},backup);
 ok(JSON.stringify(restored.storage)===JSON.stringify(backup.storage)&&restored.other==='untouched','export → clear → restore gives identical keys and values, preserving unrelated data');
 const bad=structuredClone(backup);bad.storage['zolaB.v22']=JSON.stringify({traps:{broken:{}}});
 await upload('#zbackup-file',bad);await page.waitForFunction(()=>document.querySelector('#zbackup-status').textContent.startsWith('Restore refused:'));
 ok(await page.evaluate(v=>JSON.stringify(ZOLA_BACKUP.snapshot().storage)===JSON.stringify(v.storage),backup),'corrupt backup is refused without changes');
 const different=structuredClone(backup);different.storage['zolaB.v22']=JSON.stringify({...seed,traps:{}});
 const rollback=await page.evaluate(v=>{const before=JSON.stringify(ZOLA_BACKUP.snapshot().storage),original=Storage.prototype.setItem;let thrown=false;Storage.prototype.setItem=function(k,value){if(k==='zolaCsatForge.v1'&&!thrown){thrown=true;throw new Error('Quota exceeded')}return original.call(this,k,value)};let error='';try{ZOLA_BACKUP.restore(v)}catch(e){error=e.message}finally{Storage.prototype.setItem=original}return {error,same:JSON.stringify(ZOLA_BACKUP.snapshot().storage)===before}},different);
 ok(rollback.same&&rollback.error.includes('previous data was restored'),'restore rolls back every key after a partial storage failure');
 const blocked=await page.evaluate(v=>{const before=JSON.stringify(ZOLA_BACKUP.snapshot().storage),original=Storage.prototype.setItem;Storage.prototype.setItem=function(){throw new Error('Writes unavailable')};try{ZOLA_BACKUP.restore(v)}catch(e){}finally{Storage.prototype.setItem=original}return JSON.stringify(ZOLA_BACKUP.snapshot().storage)===before},different);
 ok(blocked,'restore with blocked writes preserves every existing key');
 await upload('#zbackup-file',backup);await page.waitForFunction(()=>document.querySelector('#zbackup').open);
 await Promise.all([page.waitForEvent('load'),click('#zbackup-confirm')]);
 ok(await page.evaluate(()=>localStorage.getItem('zolaB.v22'))===previous,'confirmed restore reloads with Hacking progress intact');
 // Offline calendar without saved feed, then a custom accepted feed override.
 await ctx.unroute(/raw\.githubusercontent\.com/);await ctx.route(/raw\.githubusercontent\.com/,r=>r.abort());
 await page.evaluate(()=>{ZOLA_LIVE.forget();document.querySelector('#clock').click()});await page.waitForFunction(()=>document.querySelectorAll('#zcal li').length===4);
 ok(true,'calendar exposes all four built-in dates without a saved feed');
 const [cal]=await Promise.all([page.waitForEvent('download'),click('#zcal .zc-acts .btn:not(.ghost)')]);
 ok(fs.readFileSync(await cal.path(),'utf8').includes('DTSTART;VALUE=DATE:20270523'),'built-in dates export offline');await page.keyboard.press('Escape');
 let defaultRequests=0;await ctx.route(/raw\.githubusercontent\.com/,r=>{defaultRequests++;return r.abort()});
 const custom=JSON.parse(FEED_FIXTURE);custom.updated='2099-01-01T00:00:00Z';custom.exams[0].date='2027-05-30';
 await ctx.route('https://feed.example.test/zola.json',r=>r.fulfill({body:JSON.stringify(custom)}));
 await page.evaluate(async()=>{ZOLA_LIVE.setUrl('https://feed.example.test/zola.json');await ZOLA_LIVE.check(true);document.querySelector('#clock').click()});await page.waitForFunction(()=>document.querySelector('#zcal').textContent.includes('30 May'));
 ok(defaultRequests===0,'calendar respects custom feed overrides without fetching the default feed');await page.keyboard.press('Escape');
 const accepted=await page.evaluate(()=>JSON.stringify(ZOLA_LIVE.exams()));
 custom.updated='2099-01-02T00:00:00Z';custom.inbox[0].machines=['M99'];await ctx.route('https://feed.example.test/zola.json',r=>r.fulfill({body:JSON.stringify(custom)}));
 await page.evaluate(()=>ZOLA_LIVE.check(true));
 ok(await page.evaluate(()=>JSON.stringify(ZOLA_LIVE.exams()))===accepted,'malformed fresh feed retains the last good exam data');
 await click('.zsections');
 ok(await page.evaluate(()=>!document.querySelector('#zsections-menu').hidden&&document.querySelectorAll('#zsections-menu button').length===7),'one tap exposes all seven Forecast sections on a phone');
 await page.keyboard.press('End');await page.keyboard.press('Enter');await page.waitForTimeout(200);
 ok(page.url().endsWith('#forecast/sources')&&await page.evaluate(()=>document.querySelector('#zsections-menu').hidden),'keyboard reaches Sources and closes the section chooser');
 await click('.zsections');await page.keyboard.press('Escape');
 ok(await page.evaluate(()=>document.activeElement.classList.contains('zsections')),'Escape returns focus to the overflow button');
 await page.setViewportSize({width:1280,height:900});await page.waitForTimeout(200);
 ok(await page.locator('.zsections').isHidden(),'overflow button hides when all sections fit');
 ok(errs.length===0,'no page errors: '+errs.join(' | '));
}finally{await ctx.close();await browser.close();close();}
process.exit(failures()?1:0);
