// Owner-approved source check of every built-in tracker event (3 October 2026; option A).
// Report: docs/VERIFICATION-2026-10-03.md. Applied to the owner's dataItems at build time by tools/app-fixes.mjs.
// result: 'confirmed' (shown as Checked), 'corrected' (text fixed below, shown as Checked), 'partial' (main fact only).
// edit: { field: [text as checked, corrected text] }. A field already holding the corrected text is left alone;
// any other value means the owner changed the event, and the build stops so the check can be redone.
export const CHECKED_ON = '2026-10-03';
const S = (name, url) => ({ name, url });
export const CHECKS = [
  { id: 'TRK-001', result: 'confirmed', note: 'Defeated 17 Apr 2026, 298 to 230, short of the 352 needed; the companion Delimitation and UT Laws Bills were withdrawn.',
    src: [S('Drishti IAS, 18 Apr 2026', 'https://www.drishtiias.com/daily-updates/daily-news-analysis/defeat-of-the-constitution-131st-amendment-bill-2026/print_manually')] },
  { id: 'TRK-002', result: 'corrected', note: 'Corrected: Lok Sabha passed it on 11 Aug and Rajya Sabha on 12 Aug 2026; assent was reported on 18 Aug (not 14 Aug), and the Act came into force on 25 Aug 2026.',
    edit: { w: ['Assent 14 Aug 2026', 'Assent Aug 2026; in force 25 Aug 2026'], date: ['2026-08-14', '2026-08-25'],
      src: ['Rashtrapati Bhavan assent record, 14 Aug 2026', 'Kerala (Alteration of Name) Act, 2026; MHA notification of 25 Aug 2026'] },
    src: [S('Onmanorama, 18 Aug 2026', 'https://www.onmanorama.com/news/kerala/2026/08/18/president-murmu-gives-assent-to-bill-renaming-kerala-as-keralam.html'), S('Onmanorama, 26 Aug 2026', 'https://www.onmanorama.com/news/kerala/2026/08/26/its-official-kerala-is-now-keralam-as-centre-notifies-name-change.html')] },
  { id: 'TRK-003', result: 'confirmed', note: 'In force 1 Jul 2026: 125 days, 60:40 funding (90:10 for North-Eastern and Himalayan States).',
    src: [S('Business Standard', 'https://www.business-standard.com/india-news/vb-g-ram-g-replacing-mgnrega-to-come-into-force-across-india-from-july-1-126051100540_1.html')] },
  { id: 'TRK-004', result: 'confirmed', note: 'Houselisting Apr to Sep 2026 (30 days per State); population enumeration Feb 2027 with caste; reference dates as stated.',
    src: [S('PIB backgrounder, Apr 2026', 'https://static.pib.gov.in/WriteReadData/specificdocs/documents/2026/apr/doc2026425856601.pdf')] },
  { id: 'TRK-005', result: 'confirmed', note: 'Ordinance of May 2026 replaced; Lok Sabha 3 Aug, Rajya Sabha 5 Aug 2026; strength raised from 34 to 38 including the CJI.',
    src: [S('PRS: the Bill', 'https://prsindia.org/files/bills_acts/bills_parliament/2026/Supreme_Court_(Number_of_Judges)_(A)_Bill_2026.pdf'), S('Bar & Bench', 'https://www.barandbench.com/news/lok-sabha-passes-bill-to-increase-supreme-court-judge-strength-to-38')] },
  { id: 'TRK-006', result: 'confirmed', note: 'Introduced 27 Jul 2026: Special Task Forces, Special Fast-Track Courts (trial within three months), 60-day investigations; Nilekani task force set up.',
    src: [S('PRS Bill Track', 'https://prsindia.org/billtrack/the-public-examinations-prevention-of-unfair-means-amendment-bill-2026')] },
  { id: 'TRK-007', result: 'partial', note: "Confirmed: Bankers' Books Evidence Bill, 2026 (Lok Sabha 5 Aug, Rajya Sabha 10 Aug) and the national-honour amendment. The other Bills listed were not individually checked.",
    src: [S('PRS Bill Track', "https://prsindia.org/billtrack/the-bankers'-books-evidence-bill-2026")] },
  { id: 'TRK-008', result: 'confirmed', note: 'In force 1 Apr 2026 (passed 12 Aug 2025, assent 21 Aug 2025, Rules 20 Mar 2026); single tax year.',
    src: [S('Drishti IAS, 2 Apr 2026', 'https://www.drishtiias.com/daily-updates/daily-news-analysis/income-tax-act-2025/print_manually')] },
  { id: 'TRK-009', result: 'confirmed', note: 'GDP base 2022-23 (27 Feb 2026), CPI 2024 (12 Feb 2026), IIP 2022-23 (28 May 2026).',
    src: [S('PIB note, Jan 2026', 'https://static.pib.gov.in/WriteReadData/specificdocs/documents/2026/jan/doc2026128772801.pdf')] },
  { id: 'TRK-010', result: 'confirmed', note: 'Fiscal deficit 4.3%, capex Rs 12.2 lakh crore, Biopharma SHAKTI and the four rare-earth corridors confirmed.',
    src: [S('ICAI Journal', 'https://cajournal.icai.org/article-details/union-budget-2026-27-growth-and-structural-transformation')] },
  { id: 'TRK-011', result: 'confirmed', note: 'Concluded 27 Jan 2026; the European Commission sent it to the Council for signature on 11 Sep 2026. Not yet signed.',
    src: [S('News on AIR, 11 Sep 2026', 'https://newsonair.gov.in/india-eu-move-closer-to-fta-as-european-commission-submits-formal-proposal/')] },
  { id: 'TRK-012', result: 'confirmed', note: 'Hormuz declared closed in Mar 2026; Brent peaked near $126; LPG shortages in India; Iran-Oman understanding in Aug 2026.',
    src: [S('Onmanorama, 13 Mar 2026', 'https://www.onmanorama.com/news/world/2026/03/13/iran-indian-lpg-ships-strait-of-hormuz.html'), S('NPR, 7 Aug 2026', 'https://www.kosu.org/world-news/2026-08-07/iran-says-agreement-with-oman-for-strait-of-hormuz-prohibits-u-s-and-israeli-vessels')] },
  { id: 'TRK-013', result: 'confirmed', note: 'Make in India turned 12 on 25 Sep 2026; electronics production Rs 13.11 lakh crore in 2025-26.',
    src: [S('News on AIR, 25 Sep 2026', 'https://newsonair.gov.in/make-in-india-initiative-completes-12-years/')] },
  { id: 'TRK-014', result: 'partial', note: 'Confirmed: Samudra Manthan, Rs 84,084 crore, approved by the Cabinet on 31 Jul 2026 (60 deepwater wells, to 2030-31). PM-KISAN and Khelo India items were not individually checked.',
    src: [S('Deccan Herald', 'https://www.deccanherald.com/india/cabinet-approves-rs-84084-crore-samudra-manthan-scheme-to-boost-offshore-oil-and-gas-exploration-4094586')] },
  { id: 'TRK-015', result: 'corrected', note: 'Updated: the 18th BRICS Summit was held in New Delhi on 12-13 Sep 2026 and adopted the New Delhi Declaration.',
    edit: { w: ['2026', 'Summit 12-13 Sep 2026'], date: ['2026-01-01', '2026-09-13'],
      what: ['India chairs BRICS in 2026; the summit date and outcomes need checking.', "India chaired BRICS in 2026. The 18th Summit met in New Delhi (Bharat Mandapam) on 12-13 Sep 2026 under the theme 'Building for Resilience, Innovation, Cooperation and Sustainability' and adopted the New Delhi Declaration."] },
    src: [S('SAnews (South Africa)', 'https://www.sanews.gov.za/node/84282'), S('News on AIR, 14 Sep 2026', 'https://newsonair.gov.in/global-leaders-praise-brics-summit-under-indias-chairmanship/')] },
  { id: 'TRK-016', result: 'corrected', note: 'Corrected date: flagged off on 17 Jul 2026.', edit: { date: ['2026-07-15', '2026-07-17'] },
    src: [S('Manorama Yearbook, 29 Jul 2026', 'https://www.manoramayearbook.in/current-affairs/india/2026/07/29/direct-freight-train-from-kolkata-port-to-biratnagar.html')] },
  { id: 'TRK-017', result: 'confirmed', note: 'INS Mahendragiri commissioned 11 Jul 2026; INS Nipun commissioned 31 Aug 2026. The AK-203 detail was not rechecked.',
    src: [S('Marine Insight', 'https://www.marineinsight.com/indian-navy-commissions-sixth-indigenous-project-17a-stealth-guided-missile-frigate-ins-mahendragiri/'), S('News on AIR, 31 Aug 2026', 'https://newsonair.gov.in/indian-navy-commissions-ins-nipun-at-naval-dockyard-mumbai/')] },
  { id: 'TRK-018', result: 'confirmed', note: 'Renamed the Republic of Naoero on 4 Aug 2026; code NRU to NRO.',
    src: [S('NPR, 4 Aug 2026', 'https://www.nhpr.org/2026-08-04/nauru-the-worlds-3rd-smallest-country-changes-its-name-to-naoero')] },
  { id: 'TRK-019', result: 'corrected', note: 'Corrected: appointed on 9 May 2026 and took over at the end of May, after General Anil Chauhan\'s tenure ended on 30 May 2026.',
    edit: { w: ['Jul 2026', 'May 2026'], date: ['2026-07-15', '2026-05-31'],
      what: ['General N. S. Raja Subramani became CDS.', 'General N. S. Raja Subramani became Chief of Defence Staff and Secretary, Department of Military Affairs, succeeding General Anil Chauhan.'] },
    src: [S('News on AIR, 9 May 2026', 'https://www.newsonair.gov.in/lieutenant-general-n-s-raja-subramani-appointed-new-chief-of-defence-staff/')] },
  { id: 'TRK-020', result: 'corrected', note: 'Corrected date: designated on 3 Aug 2026.', edit: { date: ['2026-08-15', '2026-08-03'] },
    src: [S('News on AIR, 3 Aug 2026', 'https://newsonair.gov.in/glaw-lake-of-arunachal-pradesh-designated-as-101st-ramsar-site-first-in-the-state/')] },
  { id: 'TRK-021', result: 'confirmed', note: 'COP30 outcomes as stated; COP31 in Antalya, 9-20 Nov 2026, with Australia presiding over negotiations.',
    src: [S('Al Jazeera, 20 Nov 2025', 'https://www.aljazeera.com/amp/news/2025/11/20/turkiye-to-host-cop31-climate-summit-after-australia-concedes-bid')] },
  { id: 'TRK-022', result: 'confirmed', note: 'UNCCD COP17, Ulaanbaatar, 17-28 Aug 2026; India released its grasslands guide on 17 Aug.',
    src: [S('Adda247', 'https://currentaffairs.adda247.com/unccd-cop17-key-takeaways-on-grasslands-and-drought-resilience/')] },
  { id: 'TRK-023', result: 'corrected', note: 'Corrected date: notified on 19 Jun 2026 and reported on 7 Jul.', edit: { w: ['Jul 2026', 'Jun 2026'], date: ['2026-07-20', '2026-06-19'] },
    src: [S('News on AIR, 7 Jul 2026', 'https://newsonair.gov.in/mizorams-natural-history-museum-notified-as-indias-21st-designated-repository/')] },
  { id: 'TRK-024', result: 'confirmed', note: 'Rs 2.82 crore released on 22 Aug 2026 to 27 State Biodiversity Boards, 3 UT councils and ICAR-IIHR.',
    src: [S('News on AIR, 22 Aug 2026', 'https://newsonair.gov.in/national-biodiversity-authority-disburses-%e2%82%b92-82-crore-under-access-and-benefit-sharing-mechanism/')] },
  { id: 'TRK-025', result: 'corrected', note: 'Corrected date: released on 16 Jul 2026.', edit: { w: ['Aug 2026', 'Jul 2026'], date: ['2026-08-20', '2026-07-16'] },
    src: [S('GKToday', 'https://www.gktoday.in/nbsslup-develops-indias-first-soil-texture-map/')] },
  { id: 'TRK-026', result: 'confirmed', note: 'Inscribed 25 Jul 2026 at the 48th session in Busan; India\'s 45th.',
    src: [S('Outlook Traveller', 'https://www.outlooktraveller.com/News/sarnath-becomes-indias-45th-unesco-world-heritage-site')] },
  { id: 'TRK-027', result: 'confirmed', note: 'The national-honour amendment covering Vande Mataram passed the Rajya Sabha on 29 Jul 2026.',
    src: [S('IANS, 29 Jul 2026', 'https://ianslive.in/vande-mataram-bill-passed-in-rs-all-you-need-to-know--20260729175150')] },
  { id: 'TRK-028', result: 'confirmed', note: 'Born 31 Oct 1875; well-established record.', src: [] },
  { id: 'TRK-029', result: 'confirmed', note: 'Born 15 Nov 1875; Janjatiya Gaurav Varsh 2024-25; well-established record.', src: [] },
  { id: 'TRK-030', result: 'confirmed', note: 'ISRO targets G1 with Vyommitra for December 2026; crewed flight 2027.',
    src: [S('The Tribune', 'https://www.tribuneindia.com/news/india/1st-non-crew-gaganyaan-mission-to-launch-in-dec-with-robot-vyommitra')] },
  { id: 'TRK-031', result: 'partial', note: 'Confirmed: GSLV-F17 launched EOS-05, India\'s first geosynchronous imaging satellite, on 4 Sep 2026. NVS-03, the industry PSLV and Vikram-1 were not checked.',
    src: [S('The Wire', 'https://thewire.in/space/the-success-of-eos-05-says-the-seven-month-launch-hiatus-for-isro-is-over')] },
  { id: 'TRK-032', result: 'confirmed', note: '2026 ICTP Dirac Medal shared with Derrida, Mezard and Sompolinsky.',
    src: [S('ICTS', 'https://www.icts.res.in/news/deepak-dhar-awarded-prestigious-dirac-medal')] },
  { id: 'TRK-033', result: 'corrected', note: 'Updated: the committee deferred adopting its report on 17 Jul 2026, and the Lok Sabha extended its deadline to the last week of the Winter Session 2026.',
    edit: { w: ['Introduced 20 Aug 2025; JPC active to Jul 2026', 'Introduced 20 Aug 2025; JPC report due Winter Session 2026'],
      what: ['The Bill provides for removing a Prime Minister, Chief Minister or minister who stays in custody for 30 consecutive days on charges carrying five or more years of imprisonment. It was referred to a Joint Parliamentary Committee, which was still meeting in July 2026.', 'The Bill provides for removing a Prime Minister, Chief Minister or minister who stays in custody for 30 consecutive days on charges carrying five or more years of imprisonment. It was referred to a Joint Parliamentary Committee, which deferred adopting its report on 17 Jul 2026; its deadline now runs to the Winter Session 2026.'] },
    src: [S('Deccan Herald', 'https://deccanherald.com/india/joint-panel-examining-bill-to-remove-pm-cms-gets-extension-of-deadline-to-submit-report-4094349')] },
  { id: 'TRK-034', result: 'confirmed', note: 'Advisory opinion on Special Reference No. 1 of 2025 delivered 20 Nov 2025; well-established record.', src: [] },
  { id: 'TRK-035', result: 'corrected', note: 'Corrected: in Pooja Ramesh Singh v J&K Bank, the fake precedents were in the NCLT\'s order, not a party\'s filing.',
    edit: { what: ['In 2026 INSC 668 the Supreme Court dealt with a filing that relied on six non-existent or AI-generated citations and set out its response to hallucinated precedent.', 'In Pooja Ramesh Singh v J&K Bank (2026 INSC 668), the Supreme Court set aside NCLT and NCLAT orders because the NCLT had relied on fictitious, apparently AI-generated precedents. It declared zero tolerance: citing unverified AI case law is professional misconduct, and relying on it is a serious judicial lapse.'] },
    src: [S('The Law Gist', 'https://thelawgist.org/pooja-ramesh-singh-v-jammu-and-kashmir-bank-ai-hallucination-case-analysis-2026-insc-668/')] },
  { id: 'TRK-036', result: 'confirmed', note: 'CJI from 24 Nov 2025, notified 30 Oct 2025; well-established record.', src: [] },
  { id: 'TRK-037', result: 'corrected', note: 'Corrected: the Rules were notified in the Gazette on 13 Nov 2025 (PIB reported them on 14 Nov).',
    edit: { w: ['14 Nov 2025; next tranche May 2027', '13 Nov 2025; next tranche May 2027'], date: ['2025-11-14', '2025-11-13'],
      what: ['The Digital Personal Data Protection Rules, 2025 were notified on 14 Nov 2025. Commencement is phased, and the 18-month tranche falls in May 2027, the month of the Prelims.', 'The Digital Personal Data Protection Rules, 2025 were notified on 13 Nov 2025. Commencement is phased, and the 18-month tranche falls in May 2027, the month of the Prelims.'] }, src: [] },
  { id: 'TRK-038', result: 'confirmed', note: 'Rules notified 22 Apr 2026 and in force from 1 May 2026.',
    src: [S('News on AIR, 1 May 2026', 'https://newsonair.gov.in/promotion-regulation-of-online-gaming-rules-2026-comes-into-force/')] },
  { id: 'TRK-039', result: 'confirmed', note: 'In force 21 Nov 2025, consolidating 29 laws; well-established record.', src: [] },
  { id: 'TRK-040', result: 'confirmed', note: '56th GST Council, 3 Sep 2025; effective 22 Sep 2025; well-established record.', src: [] },
  { id: 'TRK-041', result: 'confirmed', note: 'Approved 16 Jul 2025 for six years, 100 districts; well-established record.', src: [] },
  { id: 'TRK-042', result: 'confirmed', note: 'Approved 1 Jul 2025; launched as PM-VBRY on 15 Aug 2025; well-established record.', src: [] },
  { id: 'TRK-043', result: 'confirmed', note: 'Approved 1 Oct 2025, Rs 11,440 crore, 2025-26 to 2030-31; well-established record.', src: [] },
  { id: 'TRK-044', result: 'confirmed', note: 'Signed 24 Jul 2025; in force 15 Jul 2026.',
    src: [S('Business Wales (UK)', 'https://businesswales.gov.wales/news-and-blog/uk-india-free-trade-agreement-now-effect')] },
  { id: 'TRK-045', result: 'confirmed', note: 'Signed 27 Apr 2026 at Bharat Mandapam; enters into force after ratification.',
    src: [S('India Briefing', 'https://www.india-briefing.com/news/india-new-zealand-fta-signed-2026-trade-commercial-investment-opportunities-44392.html')] },
  { id: 'TRK-046', result: 'confirmed', note: 'MC14 met 26-30 Mar 2026 and closed without a ministerial declaration; work moved to Geneva.',
    src: [S('World Economic Forum', 'https://www.weforum.org/stories/2026/04/mc14-yaounde-wto-trade/')] },
  { id: 'TRK-047', result: 'confirmed', note: 'In force 17 Jan 2026; well-established record.', src: [] },
  { id: 'TRK-048', result: 'corrected', note: 'Corrected: Gogabil (India\'s 94th site) was announced in Nov 2025; Patna Bird Sanctuary and Chhari-Dhand were added on 31 Jan 2026, taking India to 98.',
    edit: { what: ['Ramsar notices added Gokul Jalashay and Udaipur Jheel (Sep 2025), Gogabil Lake (Oct 2025), and Chhari Dhand and Patna Bird Sanctuary (Jan 2026).', 'Ramsar notices added Gokul Jalashay and Udaipur Jheel (Sep 2025), Gogabil Lake (Nov 2025), and Chhari Dhand and Patna Bird Sanctuary (Jan 2026).'] },
    src: [S('Drishti IAS, 10 Nov 2025', 'https://www.drishtiias.com/daily-updates/daily-news-analysis/bihars-gogabil-lake-is-indias-94th-ramsar-site/print_manually'), S('News on AIR, 31 Jan 2026', 'https://www.newsonair.gov.in/patna-bird-sanctuary-and-chhari-dhand-added-to-indias-ramsar-sites-list/')] },
  { id: 'TRK-049', result: 'confirmed', note: '22-23 Nov 2025, the first G20 summit in Africa; well-established record.', src: [] },
  { id: 'TRK-050', result: 'confirmed', note: 'Rio 6-7 Jul 2025; Tianjin 31 Aug-1 Sep 2025; well-established record.', src: [] },
  { id: 'TRK-051', result: 'confirmed', note: 'Released 17 Oct 2025 covering 109 countries; well-established record.', src: [] },
  { id: 'TRK-052', result: 'corrected', note: 'Corrected: India is 38th of 139 overall (25th on outputs, 49th on inputs). The earlier "15th in knowledge and technology outputs" could not be confirmed.',
    edit: { what: ["WIPO released GII 2026. India ranked 15th in knowledge and technology outputs; that is a sub-index rank, not India's overall rank.", "WIPO released GII 2026. India ranked 38th of 139 economies overall (25th on innovation outputs, 49th on inputs) and was an innovation 'overperformer' for the 16th year."] },
    src: [S('WIPO GII 2026 results', 'https://www.wipo.int/web-publications/global-innovation-index-2026/en/gii-2026-results.html'), S('ETV Bharat, 30 Sep 2026', 'https://www.etvbharat.com/en/technology/india-ranks-38th-in-global-innovation-index-2026-tops-south-asia-enn26093007570')] },
  { id: 'TRK-053', result: 'confirmed', note: 'Launched 30 Jul 2025 on GSLV-F16; well-established record.', src: [] },
  { id: 'TRK-054', result: 'confirmed', note: 'Lok Sabha 17 Dec, Rajya Sabha 18 Dec, assent 20 Dec 2025.',
    src: [S('World Nuclear News', 'https://world-nuclear-news.org/articles/indias-shanti-bill-completes-legislative-process')] },
  { id: 'TRK-055', result: 'corrected', note: 'Corrected: the summit week ran 16-20 Feb 2026; 89 signatories endorsed the New Delhi Declaration.', edit: { w: ['16-21 Feb 2026', '16-20 Feb 2026'] },
    src: [S('Chronicle India', 'https://www.chronicleindia.in/online-magazine/archive-csce-june-2026/india-ai-impact-summit')] },
  { id: 'TRK-056', result: 'confirmed', note: 'Splashdown 15 Jul 2025; well-established record.', src: [] },
  { id: 'TRK-057', result: 'corrected', note: 'Corrected date: inscribed on 11 Jul 2025 at the 47th session in Paris.',
    edit: { w: ['15 Jul 2025', '11 Jul 2025'], date: ['2025-07-15', '2025-07-11'], src: ['UNESCO, 15 Jul 2025', 'UNESCO World Heritage Committee, 11 Jul 2025'] }, src: [] },
];
